import type {
  EventProduct,
  EventSummary,
  LogEntry,
  Order,
  Product,
  QueueAdminRow,
  RevenuePoint,
  StockRow,
  SystemMetric,
  User,
} from '@/types'

const now = Date.now()
const hours = (h: number) => new Date(now + h * 3600_000).toISOString()

export const mockUser: User = {
  id: 'u_1',
  nickname: '테몬러버',
  email: 'temon.lover@kakao.com',
  phone: '010-1234-5678',
  point: 12800,
  createdAt: hours(-24 * 30),
}

export const mockProducts: Product[] = [
  {
    id: 'p_1',
    name: '에어라이트 러닝화',
    description: '가볍고 통기성이 뛰어난 데일리 러닝화.',
    image: '/images/products/sneaker.png',
    price: 129000,
    category: '패션',
    createdAt: hours(-240),
  },
  {
    id: 'p_2',
    name: '노이즈캔슬링 무선이어폰',
    description: '몰입감 넘치는 액티브 노이즈 캔슬링 이어폰.',
    image: '/images/products/earbuds.png',
    price: 219000,
    category: '전자기기',
    createdAt: hours(-220),
  },
  {
    id: 'p_3',
    name: '스마트워치 프로',
    description: '건강 관리와 알림을 한 번에, 올데이 배터리.',
    image: '/images/products/watch.png',
    price: 329000,
    category: '전자기기',
    createdAt: hours(-200),
  },
  {
    id: 'p_4',
    name: '리페어 앰플 세럼',
    description: '피부 장벽을 지켜주는 고농축 앰플 세럼.',
    image: '/images/products/serum.png',
    price: 48000,
    category: '뷰티',
    createdAt: hours(-180),
  },
  {
    id: 'p_5',
    name: '포터블 블루투스 스피커',
    description: '어디서나 즐기는 강력한 사운드.',
    image: '/images/products/speaker.png',
    price: 89000,
    category: '전자기기',
    createdAt: hours(-160),
  },
  {
    id: 'p_6',
    name: '데일리 백팩',
    description: '노트북 수납이 편한 미니멀 백팩.',
    image: '/images/products/backpack.png',
    price: 76000,
    category: '패션',
    createdAt: hours(-140),
  },
  {
    id: 'p_7',
    name: '컴팩트 기계식 키보드',
    description: '타건감이 살아있는 무선 기계식 키보드.',
    image: '/images/products/keyboard.png',
    price: 112000,
    category: '전자기기',
    createdAt: hours(-120),
  },
  {
    id: 'p_8',
    name: '세라믹 머그컵',
    description: '따뜻한 감성의 데일리 머그컵.',
    image: '/images/products/mug.png',
    price: 18000,
    category: '리빙',
    createdAt: hours(-100),
  },
]

export const mockEvents: EventSummary[] = [
  {
    id: 'e_1',
    title: '한정판 스니커즈 드롭',
    description: '단 3시간, 인기 스니커즈를 최대 40% 할인된 가격에!',
    image: '/images/events/sneaker-drop.png',
    status: 'OPEN',
    startAt: hours(-1),
    endAt: hours(2),
    productCount: 3,
  },
  {
    id: 'e_2',
    title: '테크 프라이데이',
    description: '이어폰, 스마트워치 등 인기 전자기기 라이브 특가.',
    image: '/images/events/tech-friday.png',
    status: 'OPEN',
    startAt: hours(-0.5),
    endAt: hours(4),
    productCount: 3,
  },
  {
    id: 'e_3',
    title: '뷰티 라이브 세일',
    description: '베스트셀러 스킨케어를 라이브로 만나보세요.',
    image: '/images/events/beauty-live.png',
    status: 'UPCOMING',
    startAt: hours(6),
    endAt: hours(10),
    productCount: 2,
  },
  {
    id: 'e_4',
    title: '홈 & 리빙 위크',
    description: '집을 채우는 감성 리빙 아이템 특가전.',
    image: '/images/events/home-living.png',
    status: 'UPCOMING',
    startAt: hours(24),
    endAt: hours(30),
    productCount: 2,
  },
]

export const mockEventProducts: EventProduct[] = [
  {
    id: 'ep_1',
    eventId: 'e_1',
    productId: 'p_1',
    name: '에어라이트 러닝화',
    image: '/images/products/sneaker.png',
    originalPrice: 129000,
    eventPrice: 77000,
    totalStock: 200,
    remainingStock: 42,
    reservedStock: 12,
    soldCount: 146,
    status: 'ON_SALE',
    description: '가볍고 통기성이 뛰어난 데일리 러닝화. 이벤트 한정 수량!',
  },
  {
    id: 'ep_2',
    eventId: 'e_1',
    productId: 'p_6',
    name: '데일리 백팩',
    image: '/images/products/backpack.png',
    originalPrice: 76000,
    eventPrice: 49000,
    totalStock: 150,
    remainingStock: 8,
    reservedStock: 4,
    soldCount: 138,
    status: 'ON_SALE',
    description: '노트북 수납이 편한 미니멀 백팩.',
  },
  {
    id: 'ep_3',
    eventId: 'e_1',
    productId: 'p_8',
    name: '세라믹 머그컵',
    image: '/images/products/mug.png',
    originalPrice: 18000,
    eventPrice: 9900,
    totalStock: 300,
    remainingStock: 0,
    reservedStock: 0,
    soldCount: 300,
    status: 'SOLD_OUT',
    description: '따뜻한 감성의 데일리 머그컵.',
  },
  {
    id: 'ep_4',
    eventId: 'e_2',
    productId: 'p_2',
    name: '노이즈캔슬링 무선이어폰',
    image: '/images/products/earbuds.png',
    originalPrice: 219000,
    eventPrice: 159000,
    totalStock: 120,
    remainingStock: 63,
    reservedStock: 7,
    soldCount: 50,
    status: 'ON_SALE',
    description: '몰입감 넘치는 액티브 노이즈 캔슬링 이어폰.',
  },
  {
    id: 'ep_5',
    eventId: 'e_2',
    productId: 'p_3',
    name: '스마트워치 프로',
    image: '/images/products/watch.png',
    originalPrice: 329000,
    eventPrice: 249000,
    totalStock: 80,
    remainingStock: 21,
    reservedStock: 5,
    soldCount: 54,
    status: 'ON_SALE',
    description: '건강 관리와 알림을 한 번에, 올데이 배터리.',
  },
  {
    id: 'ep_6',
    eventId: 'e_2',
    productId: 'p_5',
    name: '포터블 블루투스 스피커',
    image: '/images/products/speaker.png',
    originalPrice: 89000,
    eventPrice: 59000,
    totalStock: 100,
    remainingStock: 74,
    reservedStock: 2,
    soldCount: 24,
    status: 'ON_SALE',
    description: '어디서나 즐기는 강력한 사운드.',
  },
  {
    id: 'ep_7',
    eventId: 'e_3',
    productId: 'p_4',
    name: '리페어 앰플 세럼',
    image: '/images/products/serum.png',
    originalPrice: 48000,
    eventPrice: 33000,
    totalStock: 250,
    remainingStock: 250,
    reservedStock: 0,
    soldCount: 0,
    status: 'READY',
    description: '피부 장벽을 지켜주는 고농축 앰플 세럼.',
  },
  {
    id: 'ep_8',
    eventId: 'e_3',
    productId: 'p_7',
    name: '컴팩트 기계식 키보드',
    image: '/images/products/keyboard.png',
    originalPrice: 112000,
    eventPrice: 89000,
    totalStock: 90,
    remainingStock: 90,
    reservedStock: 0,
    soldCount: 0,
    status: 'READY',
    description: '타건감이 살아있는 무선 기계식 키보드.',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'o_1',
    orderNumber: 'TEMON-20240612-0001',
    userId: 'u_1',
    items: [
      {
        eventProductId: 'ep_4',
        name: '노이즈캔슬링 무선이어폰',
        image: '/images/products/earbuds.png',
        eventPrice: 159000,
        quantity: 1,
      },
    ],
    totalAmount: 159000,
    status: 'PAID',
    createdAt: hours(-48),
    paidAt: hours(-48),
  },
  {
    id: 'o_2',
    orderNumber: 'TEMON-20240610-0042',
    userId: 'u_1',
    items: [
      {
        eventProductId: 'ep_1',
        name: '에어라이트 러닝화',
        image: '/images/products/sneaker.png',
        eventPrice: 77000,
        quantity: 1,
      },
      {
        eventProductId: 'ep_3',
        name: '세라믹 머그컵',
        image: '/images/products/mug.png',
        eventPrice: 9900,
        quantity: 2,
      },
    ],
    totalAmount: 96800,
    status: 'DELIVERED',
    createdAt: hours(-120),
    paidAt: hours(-120),
  },
  {
    id: 'o_3',
    orderNumber: 'TEMON-20240608-0018',
    userId: 'u_1',
    items: [
      {
        eventProductId: 'ep_5',
        name: '스마트워치 프로',
        image: '/images/products/watch.png',
        eventPrice: 249000,
        quantity: 1,
      },
    ],
    totalAmount: 249000,
    status: 'CANCELLED',
    createdAt: hours(-200),
  },
]

// -------- 관리자 mock --------

export const mockRevenue: RevenuePoint[] = [
  { label: '월', revenue: 4200000, orders: 120 },
  { label: '화', revenue: 5100000, orders: 148 },
  { label: '수', revenue: 3900000, orders: 108 },
  { label: '목', revenue: 6300000, orders: 190 },
  { label: '금', revenue: 8800000, orders: 265 },
  { label: '토', revenue: 11200000, orders: 340 },
  { label: '일', revenue: 9600000, orders: 288 },
]

export const mockSystemMetrics: SystemMetric[] = [
  { label: 'CPU', value: 42, unit: '%', status: 'healthy' },
  { label: 'Memory', value: 68, unit: '%', status: 'warning' },
  { label: 'Redis', value: 12, unit: 'ms', status: 'healthy' },
  { label: 'Kafka Lag', value: 340, unit: 'msg', status: 'warning' },
  { label: 'WebSocket', value: 1284, unit: 'conn', status: 'healthy' },
]

export const mockLogs: LogEntry[] = [
  {
    id: 'l_1',
    timestamp: hours(-0.01),
    level: 'INFO',
    source: 'queue-service',
    message: 'event=e_1 대기열 순번 재계산 완료 (waiting=1240)',
  },
  {
    id: 'l_2',
    timestamp: hours(-0.02),
    level: 'WARN',
    source: 'stock-service',
    message: 'ep_2 재고 임계치 도달 (remaining=8)',
  },
  {
    id: 'l_3',
    timestamp: hours(-0.05),
    level: 'INFO',
    source: 'order-service',
    message: 'order=TEMON-20240612-0001 결제 완료 처리',
  },
  {
    id: 'l_4',
    timestamp: hours(-0.08),
    level: 'ERROR',
    source: 'payment-gateway',
    message: 'PG 응답 지연 감지 (latency=3200ms), 재시도 수행',
  },
  {
    id: 'l_5',
    timestamp: hours(-0.12),
    level: 'INFO',
    source: 'kafka-consumer',
    message: 'stock.updated 토픽 소비 정상 (offset=982331)',
  },
]

export function buildStockRows(): StockRow[] {
  return mockEventProducts.map((ep) => {
    const event = mockEvents.find((e) => e.id === ep.eventId)
    return {
      eventProductId: ep.id,
      productName: ep.name,
      eventTitle: event?.title ?? '-',
      totalStock: ep.totalStock,
      remainingStock: ep.remainingStock,
      reservedStock: ep.reservedStock,
      soldCount: ep.soldCount,
    }
  })
}

export function buildQueueRows(): QueueAdminRow[] {
  return mockEvents.map((e, i) => ({
    eventId: e.id,
    eventTitle: e.title,
    waitingCount: e.status === 'OPEN' ? 1200 - i * 260 : 0,
    enteredCount: e.status === 'OPEN' ? 320 - i * 40 : 0,
    gateStatus: e.status === 'OPEN' ? 'OPEN' : 'CLOSED',
  }))
}
